env:
  browser: true
  es6: true
  node: true

ignorePatterns:
  - storybook-static
  # This file triggers an eslint bug because of our {fs: false} setting in webpack config.
  # But for some reason it only happens locally, not in CI.
  - app/test/transformers/rawImportPreprocessor.ts

plugins:
  - react
  - react-hooks
  - "@typescript-eslint"
  - header
  - file-progress

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true

  ecmaVersion: 12
  sourceType: module
  project: tsconfig.json

settings:
  react:
    version: detect
  import/internal-regex: "^@foxglove"

rules:
  file-progress/activate: 1
  no-console: off # configured in no-restricted-syntax
  "@typescript-eslint/ban-ts-comment":
    - error
    # TODO: remove once we fix all TS issues
    - ts-expect-error: allow-with-description
      ts-ignore: true
      ts-nocheck: false
      ts-check: true
  # It's sometimes useful to explicitly name to guard against future changes
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/prefer-nullish-coalescing": warn
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  react/prop-types: off # Unnecessary with typescript validation
  react/no-unused-prop-types: warn
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error
  no-new-func: error
  header/header:
    - error
    - line
    - - " This Source Code Form is subject to the terms of the Mozilla Public"
      - " License, v2.0. If a copy of the MPL was not distributed with this"
      - " file, You can obtain one at http://mozilla.org/MPL/2.0/"

  curly: error
  "@typescript-eslint/no-unused-vars":
    - error
    - { vars: all, args: after-used, varsIgnorePattern: "^_", argsIgnorePattern: "^_" }
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  no-warning-comments:
    - error
    - terms: ["fixme", "xxx"]
      location: anywhere
  # Some good ones that people really should be adding to import/recommended:
  import/first: error
  import/no-useless-path-segments: error
  import/no-mutable-exports: error
  import/newline-after-import: error
  # Group imports into three groups [external, @foxglove, relative] and sort alphabetically within each group
  import/order:
    - error
    - alphabetize: { order: asc }
      newlines-between: always
      groups: [[builtin, external], [internal], [parent, sibling, index]]

  # we let typescript and webpack handle whether imports exist or not
  import/namespace: off
  import/default: off
  import/no-named-as-default: off
  import/no-named-as-default-member: off

  prefer-arrow-callback:
    - error
    - allowNamedFunctions: true
  "@typescript-eslint/no-shadow": error
  no-restricted-imports:
    - error
    - paths:
        - name: lodash
          importNames: [get]
          message: "Use optional chaining instead of lodash.get."
        - name: lodash/get
          message: "Use optional chaining instead of lodash.get."
  no-restricted-syntax:
    - error
    - selector: "MethodDefinition[kind='get'], Property[kind='get']"
      message: "Property getters are not allowed; prefer function syntax instead."
    - selector: "MethodDefinition[kind='set'], Property[kind='set']"
      message: "Property setters are not allowed; prefer function syntax instead."
    # We disable console methods here rather than using no-console so that it doesn't prohibit overrides such as "console.info = ..."
    - selector: "CallExpression[callee.object.name='console'][callee.property.name!=/^(warn|error|debug|assert)$/]"
      message: "Unexpected property on console object was called"

    # Ban `null [!=]= x` and `x [!=]= null`
    - selector: "BinaryExpression:matches([operator='=='], [operator='!=']):matches([left.type=Literal][left.raw=null], [right.type=Literal][right.raw=null])"
      message: 'Prefer "x == undefined" or "x != undefined" to check for both null and undefined.'
    # Ban `undefined [!=]= x`
    - selector: "BinaryExpression:matches([operator='=='], [operator='!='])[left.type=Identifier][left.name=undefined]"
      message: 'Prefer "x == undefined" or "x != undefined" to check for both null and undefined.'
    # Ban `==` and `!=` unless RHS is undefined
    - selector: "BinaryExpression:matches([operator='=='], [operator='!=']):not([right.type=Identifier][right.name=undefined]):not([right.type=Literal][right.raw=null])"
      message: 'Use strict equality operators "===" and "!==", except when checking for null or undefined.'

    - selector: "TSNullKeyword, Literal[raw=null]"
      message: >
        Prefer undefined instead of null. When required for React refs/components, use
        the `ReactNull` alias. Otherwise, if strictly necessary, disable this error with
        `// eslint-disable-next-line no-restricted-syntax`. For rationale, see:
        https://github.com/sindresorhus/meta/discussions/7"

  "@typescript-eslint/strict-boolean-expressions":
    - error
      # Force explicit checks that strings are empty
    - allowString: false
      # Force explicit checks that numbers are != 0 or NaN
      allowNumber: false
      # Keeps the error count manageable while we enhance type information from the flow conversion
      allowAny: true

overrides:
  - files:
      - "app/GlobalConfig.ts"
      - "app/PanelAPI/useBlockMessageByTopicWithFallback.ts"
      - "app/PanelAPI/useBlocksByTopic.ts"
      - "app/PanelAPI/useMessageReducer.ts"
      - "app/PanelAPI/useMessagesByTopic.ts"
      - "app/actions/panels.ts"
      - "app/components/AutoSizingCanvas/index.stories.tsx"
      - "app/components/AutoSizingCanvas/index.tsx"
      - "app/components/Autocomplete.tsx"
      - "app/components/Button.tsx"
      - "app/components/ButtonBase.tsx"
      - "app/components/Checkbox.tsx"
      - "app/components/ChildToggle/index.tsx"
      - "app/components/Confirm.tsx"
      - "app/components/CopyText.tsx"
      - "app/components/CopyToClipboard.tsx"
      - "app/components/DocumentDropListener.test.tsx"
      - "app/components/DocumentDropListener.tsx"
      - "app/components/Dropdown/index.tsx"
      - "app/components/EmptyState.tsx"
      - "app/components/ExpandingToolbar.tsx"
      - "app/components/ExperimentalFeatures.tsx"
      - "app/components/Flex.tsx"
      - "app/components/GlobalKeyListener.test.tsx"
      - "app/components/GlobalKeyListener.ts"
      - "app/components/GlobalVariablesMenu.tsx"
      - "app/components/GlobalVariablesTable.tsx"
      - "app/components/GradientPicker.stories.tsx"
      - "app/components/HelpModal.tsx"
      - "app/components/Icon.tsx"
      - "app/components/KeyboardShortcut.tsx"
      - "app/components/Menu/ExpandableMenu.tsx"
      - "app/components/Menu/Item.tsx"
      - "app/components/MessageOrderControls.tsx"
      - "app/components/MessagePathSyntax/MessagePathInput.tsx"
      - "app/components/MessagePathSyntax/messagePathsForDatatype.ts"
      - "app/components/MessagePathSyntax/useCachedGetMessagePathDataItems.ts"
      - "app/components/MessagePipeline/index.test.tsx"
      - "app/components/MessagePipeline/index.tsx"
      - "app/components/MessagePipeline/warnOnOutOfSyncMessages.ts"
      - "app/components/Modal.stories.tsx"
      - "app/components/NotificationDisplay.tsx"
      - "app/components/Panel.tsx"
      - "app/components/PanelLayout.tsx"
      - "app/components/PanelToolbar/index.tsx"
      - "app/components/PlaybackControls/PlaybackBarHoverTicks.tsx"
      - "app/components/PlaybackControls/PlaybackTimeDisplayMethod.tsx"
      - "app/components/PlaybackControls/index.stories.tsx"
      - "app/components/PlaybackControls/index.tsx"
      - "app/components/PlaybackControls/sharedHelpers.ts"
      - "app/components/PlaybackSpeedControls.tsx"
      - "app/components/Progress.tsx"
      - "app/components/ReactChartjs/ChartJSManager.ts"
      - "app/components/ReactChartjs/ChartJSWorker.ts"
      - "app/components/ReactChartjs/index.tsx"
      - "app/components/Select/Option.tsx"
      - "app/components/Select/Select.tsx"
      - "app/components/SelectableTimestamp.tsx"
      - "app/components/Slider.tsx"
      - "app/components/Sparkline.tsx"
      - "app/components/TextField.tsx"
      - "app/components/TextHighlight.tsx"
      - "app/components/TimeBasedChart/TimeBasedChartLegend.tsx"
      - "app/components/TimeBasedChart/TimeBasedChartTooltip.tsx"
      - "app/components/TimeBasedChart/index.tsx"
      - "app/components/Tooltip.tsx"
      - "app/components/TooltipBase.tsx"
      - "app/components/TopicToRenderMenu.tsx"
      - "app/components/Tree/TreeNode.tsx"
      - "app/components/Tree/index.tsx"
      - "app/components/ValidatedInput.tsx"
      - "app/components/input/JSONInput.tsx"
      - "app/dataProviders/ApiCheckerDataProvider.ts"
      - "app/dataProviders/BagDataProvider.ts"
      - "app/dataProviders/BrowserHttpReader.ts"
      - "app/dataProviders/CombinedDataProvider.ts"
      - "app/dataProviders/FetchReader.ts"
      - "app/dataProviders/IdbCacheReaderDataProvider.ts"
      - "app/dataProviders/IdbCacheWriterDataProvider.test.ts"
      - "app/dataProviders/IdbCacheWriterDataProvider.ts"
      - "app/dataProviders/MeasureDataProvider.ts"
      - "app/dataProviders/MemoryCacheDataProvider.test.ts"
      - "app/dataProviders/MemoryCacheDataProvider.ts"
      - "app/dataProviders/MemoryDataProvider.ts"
      - "app/dataProviders/ParseMessagesDataProvider.ts"
      - "app/dataProviders/ParsedMessageCache.ts"
      - "app/dataProviders/RenameDataProvider.ts"
      - "app/dataProviders/RewriteBinaryDataProvider.test.ts"
      - "app/dataProviders/RewriteBinaryDataProvider.ts"
      - "app/dataProviders/RpcDataProvider.ts"
      - "app/dataProviders/createGetDataProvider.ts"
      - "app/dataProviders/getRemoteBagGuid.ts"
      - "app/dataProviders/rawMessageDefinitionsToParsed.ts"
      - "app/dataProviders/standardDataProviderDescriptors.ts"
      - "app/index.tsx"
      - "app/panels/GlobalVariableSlider/index.tsx"
      - "app/panels/GlobalVariables/index.stories.tsx"
      - "app/panels/ImageView/CameraModel.ts"
      - "app/panels/ImageView/ImageCanvas.stories.tsx"
      - "app/panels/ImageView/ImageCanvas.tsx"
      - "app/panels/ImageView/index.tsx"
      - "app/panels/ImageView/renderImage.ts"
      - "app/panels/ImageView/util.ts"
      - "app/panels/Internals.tsx"
      - "app/panels/NodePlayground/BottomBar/DiagnosticsSection.tsx"
      - "app/panels/NodePlayground/BottomBar/LogsSection.tsx"
      - "app/panels/NodePlayground/BottomBar/index.tsx"
      - "app/panels/NodePlayground/Editor.tsx"
      - "app/panels/NodePlayground/Sidebar.tsx"
      - "app/panels/NodePlayground/index.tsx"
      - "app/panels/PanelList/index.stories.tsx"
      - "app/panels/PanelList/index.tsx"
      - "app/panels/Plot/PlotChart.tsx"
      - "app/panels/Plot/PlotLegend.tsx"
      - "app/panels/Plot/PlotMenu.test.ts"
      - "app/panels/Plot/index.tsx"
      - "app/panels/Publish/buildSampleMessage.ts"
      - "app/panels/Publish/index.tsx"
      - "app/panels/RawMessages/Metadata.tsx"
      - "app/panels/RawMessages/getDiff.ts"
      - "app/panels/RawMessages/getValueActionForValue.ts"
      - "app/panels/RawMessages/index.tsx"
      - "app/panels/RawMessages/utils.tsx"
      - "app/panels/StateTransitions/index.tsx"
      - "app/panels/Tab/ToolbarTab.tsx"
      - "app/panels/Tab/index.tsx"
      - "app/panels/Table/index.tsx"
      - "app/panels/ThreeDimensionalViz/CameraInfo/index.tsx"
      - "app/panels/ThreeDimensionalViz/DrawingTools/index.tsx"
      - "app/panels/ThreeDimensionalViz/FollowTFControl.tsx"
      - "app/panels/ThreeDimensionalViz/FrameCompatibility.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/GlobalVariableLink/LinkToGlobalVariable.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/GlobalVariableLink/UnlinkGlobalVariables.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/GlobalVariableLink/UnlinkWrapper.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/GlobalVariableLink/index.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/Interaction.stories.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/InteractionContextMenu.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/Interactions.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/ObjectDetails.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/PointCloudDetails.tsx"
      - "app/panels/ThreeDimensionalViz/Interactions/TopicLink.tsx"
      - "app/panels/ThreeDimensionalViz/LayoutToolbar.tsx"
      - "app/panels/ThreeDimensionalViz/PositionControl.tsx"
      - "app/panels/ThreeDimensionalViz/SceneBuilder/MessageCollector.ts"
      - "app/panels/ThreeDimensionalViz/SceneBuilder/index.ts"
      - "app/panels/ThreeDimensionalViz/SearchText.tsx"
      - "app/panels/ThreeDimensionalViz/TopicSettingsEditor/ColorPickerForTopicSettings.tsx"
      - "app/panels/ThreeDimensionalViz/TopicSettingsEditor/PointCloudSettingsEditor.tsx"
      - "app/panels/ThreeDimensionalViz/TopicSettingsEditor/PoseSettingsEditor.tsx"
      - "app/panels/ThreeDimensionalViz/TopicSettingsEditor/common.ts"
      - "app/panels/ThreeDimensionalViz/TopicSettingsEditor/index.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/Layout.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/NamespaceMenu.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/NodeName.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/TextHighlight.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/TextMiddleTruncate.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/TopicSettingsModal.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/TopicTree.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/TopicViewModeSelector.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/TreeNodeMenu.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/TreeNodeRow.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/VisibilityToggle.stories.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/VisibilityToggle.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/renderNamespaceNodes.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/renderStyleExpressionNodes.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/renderTreeNodes.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/useSceneBuilderAndTransformsData.test.tsx"
      - "app/panels/ThreeDimensionalViz/TopicTree/useSceneBuilderAndTransformsData.ts"
      - "app/panels/ThreeDimensionalViz/TopicTree/useTopicTree.ts"
      - "app/panels/ThreeDimensionalViz/TransformsBuilder.ts"
      - "app/panels/ThreeDimensionalViz/World.tsx"
      - "app/panels/ThreeDimensionalViz/commands/OccupancyGrids.tsx"
      - "app/panels/ThreeDimensionalViz/commands/PointClouds/buffers.ts"
      - "app/panels/ThreeDimensionalViz/commands/PointClouds/index.tsx"
      - "app/panels/ThreeDimensionalViz/commands/PointClouds/selection.ts"
      - "app/panels/ThreeDimensionalViz/commands/utils/index.ts"
      - "app/panels/ThreeDimensionalViz/index.tsx"
      - "app/panels/ThreeDimensionalViz/stories/storyComponents.tsx"
      - "app/panels/ThreeDimensionalViz/threeDimensionalVizUtils.ts"
      - "app/panels/ThreeDimensionalViz/utils/drawToolUtils.ts"
      - "app/panels/ThreeDimensionalViz/withTransforms.tsx"
      - "app/panels/TwoDimensionalPlot/index.tsx"
      - "app/panels/diagnostics/DiagnosticStatus.tsx"
      - "app/panels/diagnostics/DiagnosticStatusPanel.tsx"
      - "app/panels/diagnostics/DiagnosticSummary.tsx"
      - "app/panels/diagnostics/util.ts"
      - "app/players/NodePlayer.test.ts"
      - "app/players/OrderedStampPlayer.test.ts"
      - "app/players/OrderedStampPlayer.ts"
      - "app/players/RandomAccessPlayer.test.ts"
      - "app/players/RandomAccessPlayer.ts"
      - "app/players/StoryPlayer.ts"
      - "app/players/UserNodePlayer/index.ts"
      - "app/players/UserNodePlayer/nodeTransformerWorker/transformer.test.ts"
      - "app/players/UserNodePlayer/nodeTransformerWorker/transformer.ts"
      - "app/players/UserNodePlayer/nodeTransformerWorker/typegen.ts"
      - "app/players/UserNodePlayer/nodeTransformerWorker/typescript/ast.ts"
      - "app/players/UserNodePlayer/nodeTransformerWorker/typescript/userUtils/markers.ts"
      - "app/players/UserNodePlayer/nodeTransformerWorker/typescript/userUtils/time.ts"
      - "app/players/automatedRun/AutomatedRunPlayer.test.ts"
      - "app/players/automatedRun/AutomatedRunPlayer.ts"
      - "app/players/automatedRun/performanceMeasuringClient.ts"
      - "app/players/automatedRun/videoRecordingClient.ts"
      - "app/players/nodes.ts"
      - "app/reducers/panels.ts"
      - "app/shared/layout.ts"
      - "app/shared/validators.ts"
      - "app/store/getGlobalStore.ts"
      - "app/stories/PanelSetup.tsx"
      - "app/stories/PanelSetupWithBag.tsx"
      - "app/stories/storyHelpers.tsx"
      - "app/test/MemoryStorage.ts"
      - "app/test/setup.ts"
      - "app/util/CachedFilelike.ts"
      - "app/util/FakeRpc.ts"
      - "app/util/Logger.ts"
      - "app/util/MessageReaderStore.ts"
      - "app/util/RpcWorkerUtils.ts"
      - "app/util/Storage.ts"
      - "app/util/VirtualLRUBuffer.ts"
      - "app/util/addMessageDefaults.ts"
      - "app/util/bagConnectionsHelper.ts"
      - "app/util/bags.ts"
      - "app/util/binaryObjects/binaryTranslation/index.ts"
      - "app/util/binaryObjects/binaryWrapperObjects.ts"
      - "app/util/binaryObjects/index.ts"
      - "app/util/binaryObjects/jsWrapperObjects.ts"
      - "app/util/binaryObjects/messageDefinitionUtils.ts"
      - "app/util/clipboard.ts"
      - "app/util/datatypes.ts"
      - "app/util/errors.ts"
      - "app/util/formatTime.ts"
      - "app/util/fuzzyFilter.ts"
      - "app/util/getGlobalVariablesFromUrl.ts"
      - "app/util/getNewConnection.ts"
      - "app/util/hooks.tsx"
      - "app/util/inAutomatedRunMode.ts"
      - "app/util/index.ts"
      - "app/util/indexeddb/Database.ts"
      - "app/util/indexeddb/DbWriter.ts"
      - "app/util/indexeddb/MetaDatabase.ts"
      - "app/util/installDevtoolsFormatters.ts"
      - "app/util/layout.ts"
      - "app/util/naturalSort.ts"
      - "app/util/parseMessageDefinitionsCache.ts"
      - "app/util/performanceMeasurements.ts"
      - "app/util/quaternionToEuler.ts"
      - "app/util/ranges.ts"
      - "app/util/rosDatatypesToMessageDefinition.ts"
      - "app/util/rosDatatypesToMessageDefinitions.test.ts"
      - "app/util/selectors.ts"
      - "app/util/sendNotification.ts"
      - "app/util/stateHistory.ts"
      - "app/util/synchronizeMessages.ts"
      - "app/util/time.ts"
    rules:
      "@typescript-eslint/strict-boolean-expressions": off
