name: Auto Tag and Bump Version

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  bump_and_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - run: corepack enable

      - name: Install dependencies
        run: yarn install --mode skip-build
        env:
          # yarn runs in immutable mode "by default" in CI -- turning this off requires an
          # undocumented env var
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Bump version and create tag
        run: yarn version --patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes and tags
        run: |
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
